version: '3'
services:
  request-chain-daemon:
    expose:
      - "26657"
    image: request-chain
    command: ["rcd", "start", "--minimum-gas-prices", "0.0001stake", "--rpc.laddr", "tcp://0.0.0.0:26657"]
  request-chain-cli:
    expose:
      - "1317"
    image: request-chain
    command: ["rccli", "rest-server", "--trust-node", '--laddr=tcp://0.0.0.0:1317']
    links:
      - "request-chain-daemon:rcd"
  request-node:
    expose:
      - "3000"
    image: request-node
    command: ["node", "dist/server.js"]
    environment:
    - RCCLI_URL=http://rccli:1317
    - CHAIN_ID=wacken
    - ACCOUNT_NUMBER=1
    - ACCOUNT_NAME=perrine
    - ACCOUNT_PASSWORD=hahahaha
    - ACCOUND_ADDRESS=cosmos1xnvwlt8zh6s0gg9vnxw2yj2vxdn070kt7v9akf
    ports:
      - "3000:3000"
    links:
      - "request-chain-cli:rccli"
