apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /usr/local/Cellar/kompose/1.19.0/bin/kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: request-chain-cli
  name: request-chain-cli
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /usr/local/Cellar/kompose/1.19.0/bin/kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: request-chain-cli
    spec:
      containers:
      - args:
        - rccli
        - rest-server
        - --trust-node
        - --laddr=tcp://0.0.0.0:1317
        image: ltacker/request-chain
        name: request-chain-cli
        resources: {}
      restartPolicy: Always
status: {}
