apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /usr/local/Cellar/kompose/1.19.0/bin/kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: request-node
  name: request-node
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: request-node
status:
  loadBalancer: {}
